ACTION_DO_NOTHING = 'donothing'
ACTION_SELECT_DRONE = 'selectdrone'
ACTION_SELECT_LARVA = 'selectlarva'
ACTION_SELECT_HATCHERY = 'selecthatchery'
ACTION_BUILD_DRONE = 'builddrone'
ACTION_BUILD_ZERGLING = 'buildzergling'
ACTION_BUILD_SPAWNINGPOOL = 'buildspawningpool'
ACTION_SELECT_ARMY = 'selectarmy'
ACTION_ATTACK = 'attack'

smart_actions = [
    ACTION_DO_NOTHING,
    ACTION_SELECT_DRONE,
    ACTION_SELECT_LARVA,
    ACTION_SELECT_HATCHERY,
    ACTION_BUILD_DRONE,
    ACTION_BUILD_SPAWNINGPOOL,
    ACTION_BUILD_ZERGLING,
    ACTION_SELECT_ARMY,
    ACTION_ATTACK
]