ACTION_DO_NOTHING = 'donothing'
ACTION_SELECT_DRONE = 'selectdrone'
ACTION_SELECT_LARVA = 'selectlarva'
ACTION_SELECT_HATCHERY = 'selecthatchery'
ACTION_BUILD_DRONE = 'builddrone'
ACTION_BUILD_ZERGLING = 'buildzergling'
ACTION_BUILD_OVERLORD = 'buildoverlord'
ACTION_BUILD_QUEEN = 'buildqueen'
ACTION_BUILD_SPAWNINGPOOL = 'buildspawningpool'
ACTION_BUILD_EXTRACTOR = 'buildextractor'
ACTION_SELECT_ARMY = 'selectarmy'
ACTION_ATTACK = 'attack'
ACTION_ASSIGN_DRONE_TO_GAS = 'assigndronetogas'
ACTION_ASSIGN_DRONE_TO_MINERALS = 'assigndronetominerals'
ACTION_BUILD_HATCHERY = 'buildhatchery'


smart_actions = [
  #  ACTION_DO_NOTHING,
  # ACTION_SELECT_DRONE,
  #  ACTION_SELECT_LARVA,
  #  ACTION_SELECT_HATCHERY,
    ACTION_BUILD_DRONE,
    ACTION_BUILD_SPAWNINGPOOL,
    ACTION_BUILD_EXTRACTOR,
    ACTION_BUILD_ZERGLING,
    ACTION_BUILD_OVERLORD,
    ACTION_ASSIGN_DRONE_TO_GAS,
    ACTION_ASSIGN_DRONE_TO_MINERALS,
    ACTION_BUILD_QUEEN,
    ACTION_BUILD_HATCHERY
  #  ACTION_SELECT_ARMY,
    # ACTION_ATTACK
]